### ISSUE TITLE
Improved version of Beastie

### ISSUE THREAD

**Issue by Alayan-stk-2** [STK-helper/stk-code#36]
It is one of the lower quality kart of STK 0.9.3, an improved version would be nice.

There is already a WIP version by Jymis: https://cdn.discordapp.com/attachments/376132466152308738/451746569482665985/beastie.zip

(edit from QwertyChouskie: Benau seemed to be looking into this last I checked.)

**Comment by qwertychouskie** [comment]
Finished, Jymis's Beastie is now in-game.
