### ISSUE TITLE
Bad looking skin in high resolution

### ISSUE THREAD

**Issue by CodingJellyfish** [STK-helper/stk-code#42]
![Screenshot_20190630_205554](https://user-images.githubusercontent.com/35170687/60396884-794dca00-9b79-11e9-8684-0106d2ba620f.png)

**Comment by qwertychouskie** [comment]
@dumaosen Are you pulling and compiling the whole branch or just copying the skin to an existing install?  The skin uses new features specific to my branch, such as icon theming support and `h_inner_padding`/`v_inner_padding`.

**Comment by qwertychouskie** [comment]
From IRC:
> <dumao> no it's impossible for me to use the whole branch(Too slow net)

Closing for now, please ping me if it's still an issue with a build of the full branch.

**Comment by CodingJellyfish** [comment]
![Screenshot_20190702_191057](https://user-images.githubusercontent.com/35170687/60508512-43395300-9cfd-11e9-9bb3-b157da5bf2f3.png)

**Comment by qwertychouskie** [comment]
I'll take a look at this.  I fixed a similar issue in the credits screen by changing how the height was calculated (`height="fit"` instead of `"proportion="1"` on the containing `div`), but it may be harder here.

**Comment by qwertychouskie** [comment]
@CodingJellyfish Is this fixed in the version in upstream?
