### ISSUE TITLE
thin chinese font in new skin

### ISSUE THREAD

**Issue by CodingJellyfish** [STK-helper/stk-code#43]
![Screenshot_20190702_173011](https://user-images.githubusercontent.com/35170687/60502555-a07ad780-9cf0-11e9-91d5-93a8bace4919.png)

**Comment by qwertychouskie** [comment]
Fixed in https://github.com/STK-helper/stk-code/commit/f636893421708fa69f9def8aed3c173a897b730a and https://github.com/STK-helper/stk-code/commit/cc3912d00690b2b63ef4bdcd6c27e6f2bc261511.

**Comment by nabildebbah23** [comment]
Wow
