### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by codic12** [STK-helper/stk-code#45]
@qwertychouskie recently, better IPv6 support has been added to STK. I use this with STK from git, but your branch has not merged changes.
Can you try to merge changes from git master daily, or every 3-4 days?
Alternatively, can you make a PR to include your skin and icon theme support in master?

**Comment by qwertychouskie** [comment]
Fixed in latest merge.

**Comment by codic12** [comment]
Ok, thanks!
